# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyHouse' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'RxSwift',    '~> 3.0'
pod 'RxCocoa',    '~> 3.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

pod "RxRealm"
end

# RxTests and RxBlocking make the most sense in the context of unit/integration tests
target ‘MyHouseTests’ do
use_frameworks!
    pod 'RxBlocking', '~> 3.0'
    pod 'RxTest',     '~> 3.0'
end
